### ISSUE TITLE
TYPO3 9 compatible Version

### ISSUE THREAD

**Issue by marclindemann** [CDRO/simulatebe#6]
hi,
do you plan to update this extension für TYPO3 9?

**Comment by CDRO** [comment]
Yes, I do intend to update the extension but I haven't had time to look into it yet.

Frankly this might take some time since I usually make these updates together with customer projects, so it might take a while.

If you're in a hurry, you're welcome to contribute if you wish, I'll gladly review your changes and make them available to everybody in an official TER release.

Best REgards
Tizian
